# Generated by Django 4.0.5 on 2022-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content_post_created_on_post_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
